version: '3.9'

services:
  redis:
    container_name: ol-redis
    image: redis:${REDIS_VERSION}
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - rddata:/data
    networks:
      - rate_limiter

  postgres:
    container_name: ol-postgres
    image: postgres:${POSTGRES_VERSION}
    restart: on-failure
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rate_limiter

volumes:
  pgdata:
  rddata:

networks:
  rate_limiter:
    driver: bridge